# Artificial Neural Network

### Importing the libraries

In [65]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [66]:
tf.__version__

'2.4.0'

## Data Preprocessing

### Importing the dataset

In [67]:
dataset = pd.read_csv('Churn_Modelling.csv')

### Exploring the dataset

In [68]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [69]:
dataset.tail()

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[5 rows x 14 columns]

In [70]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [71]:
len(dataset.columns)

14

In [72]:
len(dataset)

10000

In [73]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [74]:
dataset.describe()

RowNumber    CustomerId  ...  EstimatedSalary        Exited
count  10000.00000  1.000000e+04  ...     10000.000000  10000.000000
mean    5000.50000  1.569094e+07  ...    100090.239881      0.203700
std     2886.89568  7.193619e+04  ...     57510.492818      0.402769
min        1.00000  1.556570e+07  ...        11.580000      0.000000
25%     2500.75000  1.562853e+07  ...     51002.110000      0.000000
50%     5000.50000  1.569074e+07  ...    100193.915000      0.000000
75%     7500.25000  1.575323e+07  ...    149388.247500      0.000000
max    10000.00000  1.581569e+07  ...    199992.480000      1.000000

[8 rows x 11 columns]

### Creating the Dependent and Independent Variables while dropping the unnecessary columns

In [75]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [76]:
#Check
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [77]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [78]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [79]:
#Check
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [80]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [81]:
#Check
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Feature Scaling

In [82]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [83]:
#Check
print(X)

[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


### Splitting the dataset into the Training set and Test set

In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Building the ANN

### Initializing the ANN

In [85]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [86]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#ann.add(tf.keras.layers.Dropout(0.1))

### Adding the second hidden layer

In [87]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#ann.add(tf.keras.layers.Dropout(0.1))

### Adding the output layer

In [88]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

### Compiling the ANN

In [89]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [91]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 994us/step - loss: 0.5648 - accuracy: 0.7731
Epoch 2/100
250/250 [==============================] - 0s 894us/step - loss: 0.4892 - accuracy: 0.7944
Epoch 3/100
250/250 [==============================] - 0s 952us/step - loss: 0.4649 - accuracy: 0.7958
Epoch 4/100
250/250 [==============================] - 0s 960us/step - loss: 0.4604 - accuracy: 0.7928
Epoch 5/100
250/250 [==============================] - 0s 879us/step - loss: 0.4419 - accuracy: 0.8013
Epoch 6/100
250/250 [==============================] - 0s 925us/step - loss: 0.4307 - accuracy: 0.8079
Epoch 7/100
250/250 [==============================] - 0s 857us/step - loss: 0.4264 - accuracy: 0.8141
Epoch 8/100
250/250 [==============================] - 0s 985us/step - loss: 0.4352 - accuracy: 0.8052
Epoch 9/100
250/250 [==============================] - 0s 899us/step - loss: 0.4158 - accuracy: 0.8148
Epoch 10/100
250/250 [==============================] - 0s 891us/step - l

In [92]:
ann.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (32, 6)                   78        
_________________________________________________________________
dense_7 (Dense)              (32, 6)                   42        
_________________________________________________________________
dense_8 (Dense)              (32, 1)                   7         
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________


## Making the predictions and evaluating the model

### Predicting the Test set results

In [93]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [94]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1522   73]
 [ 205  200]]


In [95]:
accuracy_score(y_test, y_pred)

0.861

## Making a prediction using model

In [96]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


## Evaluating the model

### Applying kfold cross validation

In [99]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
def build_classifier():
    classifier = tf.keras.models.Sequential()
    classifier.add(tf.keras.layers.Dense(units=6, activation='relu'))
    classifier.add(tf.keras.layers.Dense(units=6, activation='relu'))
    classifier.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 100)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
mean = accuracies.mean()
variance = accuracies.std()

Epoch 1/100
720/720 [==============================] - 1s 902us/step - loss: 0.5383 - accuracy: 0.7725
Epoch 2/100
720/720 [==============================] - 1s 943us/step - loss: 0.4540 - accuracy: 0.7942
Epoch 3/100
720/720 [==============================] - 1s 964us/step - loss: 0.4240 - accuracy: 0.8026
Epoch 4/100
720/720 [==============================] - 1s 982us/step - loss: 0.4153 - accuracy: 0.8019
Epoch 5/100
720/720 [==============================] - 1s 964us/step - loss: 0.4158 - accuracy: 0.7895
Epoch 6/100
720/720 [==============================] - 1s 933us/step - loss: 0.4088 - accuracy: 0.8206
Epoch 7/100
720/720 [==============================] - 1s 951us/step - loss: 0.4030 - accuracy: 0.8212
Epoch 8/100
720/720 [==============================] - 1s 899us/step - loss: 0.4124 - accuracy: 0.8209
Epoch 9/100
720/720 [==============================] - 1s 909us/step - loss: 0.3934 - accuracy: 0.8373
Epoch 10/100
720/720 [==============================] - 1s 893us/step - l

In [100]:
print("Accuracy: {:.2f} %".format(mean*100))
print("Standard Deviation: {:.2f} %".format(variance*100))

Accuracy: 85.69 %
Standard Deviation: 1.02 %


## Improving the model by doing Parameter Tuning

In [101]:
#from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
def build_classifier(optimizer):
    classifier = tf.keras.models.Sequential()
    classifier.add(tf.keras.layers.Dense(units=6, activation='relu'))
    classifier.add(tf.keras.layers.Dense(units=6, activation='relu'))
    classifier.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier)
parameters = {'batch_size': [25, 32],
              'epochs': [100, 500],
              'optimizer': ['adam', 'rmsprop']}
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)
grid_search = grid_search.fit(X_train, y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

Epoch 1/100
288/288 [==============================] - 1s 887us/step - loss: 0.7772 - accuracy: 0.4740
Epoch 2/100
288/288 [==============================] - 0s 845us/step - loss: 0.4719 - accuracy: 0.7962
Epoch 3/100
288/288 [==============================] - 0s 903us/step - loss: 0.4398 - accuracy: 0.8019
Epoch 4/100
288/288 [==============================] - 0s 890us/step - loss: 0.4382 - accuracy: 0.8045
Epoch 5/100
288/288 [==============================] - 0s 848us/step - loss: 0.4380 - accuracy: 0.7992
Epoch 6/100
288/288 [==============================] - 0s 911us/step - loss: 0.4411 - accuracy: 0.8064
Epoch 7/100
288/288 [==============================] - 0s 875us/step - loss: 0.4240 - accuracy: 0.8168
Epoch 8/100
288/288 [==============================] - 0s 906us/step - loss: 0.4165 - accuracy: 0.8137
Epoch 9/100
288/288 [==============================] - 0s 919us/step - loss: 0.4107 - accuracy: 0.8212
Epoch 10/100
288/288 [==============================] - 0s 943us/step - l

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Streaming output truncated to the last 5000 lines.
Epoch 101/500
225/225 [==============================] - 0s 938us/step - loss: 0.3324 - accuracy: 0.8627
Epoch 102/500
225/225 [==============================] - 0s 887us/step - loss: 0.3296 - accuracy: 0.8638
Epoch 103/500
225/225 [==============================] - 0s 902us/step - loss: 0.3405 - accuracy: 0.8604
Epoch 104/500
225/225 [==============================] - 0s 919us/step - loss: 0.3274 - accuracy: 0.8690
Epoch 105/500
225/225 [==============================] - 0s 923us/step - loss: 0.3349 - accuracy: 0.8599
Epoch 106/500
225/225 [==============================] - 0s 942us/step - loss: 0.3324 - accuracy: 0.8600
Epoch 107/500
225/225 [==============================] - 0s 927us/step - loss: 0.3300 - accuracy: 0.8643
Epoch 108/500
225/225 [==============================] - 0s 873us/step - loss: 0.3377 - accuracy: 0.8606
Epoch 109/500
225/225 [==============================] - 0s 946us/step - loss: 0.3359 - accuracy: 0.8605
Epoc

In [102]:
print(best_parameters)
print(best_accuracy)

{'batch_size': 25, 'epochs': 100, 'optimizer': 'rmsprop'}
0.8618749999999998
